#!/bin/sh

# Синхронизация каталогов с рабочими файлами:
# * рабочие файлы postfix (обычно /var/spool/postfix)
# * логи SMTP, IMAP/POP3, HTTP, DNS и прочих служб
# * почтовые ящики виртуальных аккаунтов (/var/mail/virtual)

